/* ------------------ Read invoice_id from URL ------------------ */
const params = new URLSearchParams(window.location.search);
const invoiceId = params.get('id');

if (!invoiceId) {
  alert('Invoice not specified');
  window.location.href = '/dashboard';
  throw new Error('invoice_id missing');
}

/* ------------------ Elements ------------------ */
const box = document.getElementById('invoiceBox');

/* ------------------ Utility: Show Alert ------------------ */
function showAlert(message, type = 'success') {
  if (!document.body) return;

  const alert = document.createElement('div');
  alert.className = `alert alert-${type}`;
  alert.textContent = message;
  document.body.appendChild(alert);

  setTimeout(() => {
    alert.classList.add('fade-out');
    setTimeout(() => alert.remove(), 300);
  }, 3000);
}

/* ------------------ Fetch & Render Invoice ------------------ */
async function loadInvoice() {
  if (!box) return;

  try {
    const res = await fetch(`/api/invoices/${invoiceId}`, { credentials: 'include' });
    if (!res.ok) throw new Error('Failed to fetch invoice');

    const data = await res.json();

    box.innerHTML = `
      <h3>Invoice ${data.id || '—'}</h3>
      <p><strong>Client:</strong> ${data.client?.name || '—'}</p>
      <p><strong>Invoice Date:</strong> ${data.invoiceDate || '—'}</p>
      <p><strong>Due Date:</strong> ${data.dueDate || '—'}</p>
      <p><strong>Amount:</strong> ₹${data.amount?.toLocaleString() || '—'}</p>
      <p>${data.notes || ''}</p>
    `;
  } catch (err) {
    console.error('Invoice load error:', err);
    alert('Failed to load invoice');
    window.location.href = '/dashboard';
  }
}

/* ------------------ Button Handlers ------------------ */
document.getElementById('saveDraft')?.addEventListener('click', () => {
  showAlert('Draft saved (no PDF generated)');
  window.location.href = '/dashboard';
});

document.getElementById('finalSave')?.addEventListener('click', () => {
  showAlert('Invoice saved & PDF will be generated by backend');
  window.location.href = '/dashboard';
});

/* ------------------ Init ------------------ */
loadInvoice();
